# D-prime data selection with SQL

In [32]:
#@title Connect to Drive and build the SQL catalog { display-mode: "form" }
import os
import sys

try:
    from google.colab import drive as google_drive
except ImportError:
    pass
else:
    google_drive.mount("/content/drive", force_remount=False)
CODE = os.environ.get(
    "ZHONGDB_CODE",
    "/content/drive/MyDrive/Zhong et al. 2025 - Neuromatch Team Workspace/code",
)
if CODE not in sys.path:
    sys.path.insert(0, CODE)

sys.modules.pop("drive", None)
import drive

db = drive.setup()
db.schema()

             table  rows  columns
0  experiment_rows   142       17
1      experiments    23        6
2            files   297       11
3      memberships   133        8
4             mice    19        6
5  recording_files   400       11
6       recordings    89       14
7          release     1        7

## What can be queried?

`schema()` is the only inventory to remember. The most useful joins are:

- `experiments → memberships → recordings → mice`
- `recordings → recording_files → files`
- `experiment_rows` when the original fields from `Imaging_Exp_info.npy` matter

In [33]:
db.schema()

             table  rows  columns
0  experiment_rows   142       17
1      experiments    23        6
2            files   297       11
3      memberships   133        8
4             mice    19        6
5  recording_files   400       11
6       recordings    89       14
7          release     1        7

In [34]:
db.query("SELECT * from experiment_rows LIMIT 4")

,experiment,source_row,recording_id,retinotopy_id,mouse,date,block,session_number,is_2p,gender,reward_type,stimulus,stimulus_type,depth_json,stimulus_ids_json,note,source_json
0,naive_test1,5,LZ13_2024_05_15_1,LZ13_2024_05_15,LZ13,2024_05_15,1,1.0,True,Female,None,"cirlce0,circle1,leaf0,leaf1,leaf2",None,"[240, 200]","[0.0, 1.0, 2.0, 3.0, null]",VR move when run,"{""Gender"": ""Female"", ""Note"": ""VR move when run..."
1,naive_test1,6,LZ13_2024_05_16_2,LZ13_2024_05_16,LZ13,2024_05_16,2,2.0,True,Female,None,"rock0,rock1,brick0,brick1,brick5",None,"[240, 200]","[0.0, 1.0, 2.0, 3.0, null]",VR move when run,"{""Gender"": ""Female"", ""Note"": ""VR move when run..."
2,naive_test1,7,LZ16_2024_05_18_2,LZ16_2024_05_18,LZ16,2024_05_18,2,1.0,True,Female,None,"cirlce0,circle1,circle2,leaf0,leaf1,leaf2",None,"[240, 200]","[0.0, 1.0, null, 2.0, 3.0, null]",VR move when run,"{""Gender"": ""Female"", ""Note"": ""VR move when run..."
3,naive_test1,8,LZ16_2024_05_19_1,LZ16_2024_05_19,LZ16,2024_05_19,1,2.0,True,Female,None,"rock0,rock1,brick0,brick1,brick5",None,"[240, 200]","[0.0, 1.0, 2.0, 3.0, null]",VR move when run,"{""Gender"": ""Female"", ""Note"": ""VR move when run..."

In [35]:
db.query("SELECT * FROM experiments LIMIT 4")

    experiment      cohort  stage    moment  recording_count  mouse_count
0  naive_test1       naive  test1  snapshot               11            9
1  naive_test2       naive  test2  snapshot                7            7
2  naive_test3       naive  test3  snapshot                5            3
3    sup_test1  supervised  test1  snapshot                5            5

In [36]:
db.query("SELECT * FROM files LIMIT 4")

,filename,figshare_file_id,category,experiment,recording_id,retinotopy_id,size_bytes,size_mib,size_gib,md5,relative_path
0,Beh_naive_test1.npy,54183923,imaging_behavior,naive_test1,None,None,432561586,412.522875,0.402854,c582b1937ee1917dce1512036b346ba3,data/Beh_naive_test1.npy
1,Beh_naive_test2.npy,54183908,imaging_behavior,naive_test2,None,None,286584765,273.308530,0.266903,b622db42667fb01b433eef841dd58599,data/Beh_naive_test2.npy
2,Beh_naive_test3.npy,54183926,imaging_behavior,naive_test3,None,None,430048721,410.126420,0.400514,6261f3c6f0da26630522ca6d0724e4a9,data/Beh_naive_test3.npy
3,Beh_no_pretrain.npy,54183929,faster_learning_behavior,no_pretrain,None,None,397113022,378.716490,0.369840,684ecad53dea35d4986927c36800fa52,data/Beh_no_pretrain.npy

In [37]:
db.query("SELECT * FROM memberships LIMIT 4")

,experiment,cohort,recording_id,retinotopy_id,mouse,date,block,source_row_count
0,naive_test1,naive,LZ13_2024_05_15_1,LZ13_2024_05_15,LZ13,2024_05_15,1,1
1,naive_test1,naive,LZ13_2024_05_16_2,LZ13_2024_05_16,LZ13,2024_05_16,2,1
2,naive_test1,naive,LZ16_2024_05_18_2,LZ16_2024_05_18,LZ16,2024_05_18,2,1
3,naive_test1,naive,LZ16_2024_05_19_1,LZ16_2024_05_19,LZ16,2024_05_19,1,1

In [38]:
db.query("SELECT * FROM mice LIMIT 4")

,mouse,primary_cohort,cohorts_json,recording_count,has_full_neural,has_reduced_neural
0,DR10,unsupervised,"[""unsupervised""]",6,True,True
1,DR15,unsupervised,"[""unsupervised""]",5,True,True
2,LZ13,grating,"[""grating"", ""naive""]",4,True,True
3,LZ16,grating,"[""grating"", ""naive""]",4,True,True

In [39]:
db.query("SELECT * FROM recording_files LIMIT 4")

,recording_id,experiment,layer,filename,figshare_file_id,category,size_bytes,size_mib,size_gib,md5,relative_path
0,DR10_2022_07_12_1,unsup_train1_before_learning,behavior,Beh_unsup_train1_before_learning.npy,54183914,imaging_behavior,308224980,293.946247,0.287057,a24dd14d900228ca37f6c9cdbe49e762,data/Beh_unsup_train1_before_learning.npy
1,DR10_2022_07_12_1,None,full_neural,DR10_2022_07_12_1_neural_data.npy,54184778,full_neural,7384433945,7042.344995,6.877290,f632e105fccc0b629f2be62aced34347,data/DR10_2022_07_12_1_neural_data.npy
2,DR10_2022_07_12_1,None,reduced_neural,DR10_2022_07_12_1_SVD_dec.npy,54866219,reduced_neural,143895262,137.229216,0.134013,461787c8e0ac2e8700f5f5b4669d2418,data/DR10_2022_07_12_1_SVD_dec.npy
3,DR10_2022_07_12_1,None,retinotopy,DR10_2022_07_12_trans.npz,54183980,retinotopy,2330690,2.222719,0.002171,44890105820924b884693bdbd206e4b7,data/DR10_2022_07_12_trans.npz

In [40]:
db.query("SELECT * FROM recordings LIMIT 4")

,recording_id,retinotopy_id,mouse,date,block,experiment_count,experiments_json,has_behavior,has_reduced_neural,has_full_neural,has_retinotopy,linked_file_count,linked_bytes,linked_gib
0,DR10_2022_07_12_1,DR10_2022_07_12,DR10,2022_07_12,1,1,"[""unsup_train1_before_learning""]",True,True,True,True,4,7838884877,7.300530
1,DR10_2022_07_19_1,DR10_2022_07_19,DR10,2022_07_19,1,1,"[""unsup_train1_after_learning""]",True,True,True,True,4,5344358197,4.977321
2,DR10_2022_07_21_1,DR10_2022_07_21,DR10,2022_07_21,1,2,"[""unsup_test1"", ""unsup_train2_before_learning""]",True,True,True,True,5,5458290704,5.083429
3,DR10_2022_07_28_1,DR10_2022_07_28,DR10,2022_07_28,1,1,"[""unsup_train2_after_learning""]",True,True,True,True,4,4393936204,4.092172

In [41]:
db.query("SELECT * FROM release LIMIT 4")

,article_id,version,file_count,total_bytes,doi,title,root
0,28811129,2,297,452233500962,10.25378/janelia.28811129.v2,Unsupervised pretraining in biological neural ...,<NA>

In [42]:
db.schema()

             table  rows  columns
0  experiment_rows   142       17
1      experiments    23        6
2            files   297       11
3      memberships   133        8
4             mice    19        6
5  recording_files   400       11
6       recordings    89       14
7          release     1        7

In [43]:
db.query("select distinct(experiment) from experiments order by experiment")

                      experiment
0                    naive_test1
1                    naive_test2
2                    naive_test3
3                      sup_test1
4                      sup_test2
5                      sup_test3
6      sup_train1_after_learning
7     sup_train1_before_learning
8      sup_train2_after_learning
9     sup_train2_before_learning
10           test1_after_grating
11          test1_before_grating
12           test2_after_grating
13          test2_before_grating
14          train1_after_grating
15         train1_before_grating
16                   unsup_test1
17                   unsup_test2
18                   unsup_test3
19   unsup_train1_after_learning
20  unsup_train1_before_learning
21   unsup_train2_after_learning
22  unsup_train2_before_learning

In [44]:
# The 23 supplied experiment labels (the equivalent of info.keys()).
db.query("""
    SELECT cohort, stage, moment, experiment, recording_count, mouse_count
    FROM experiments
    ORDER BY cohort, stage, moment, experiment
""")

,cohort,stage,moment,experiment,recording_count,mouse_count
0,grating,test1,after,test1_after_grating,5,3
1,grating,test1,before,test1_before_grating,5,3
2,grating,test2,after,test2_after_grating,5,3
3,grating,test2,before,test2_before_grating,5,3
4,grating,train1,after,train1_after_grating,5,3
5,grating,train1,before,train1_before_grating,5,3
6,naive,test1,snapshot,naive_test1,11,9
7,naive,test2,snapshot,naive_test2,7,7
8,naive,test3,snapshot,naive_test3,5,3
9,supervised,test1,snapshot,sup_test1,5,5
10,supervised,test2,snapshot,sup_test2,5,5
11,supervised,test3,snapshot,sup_test3,5,3
12,supervised,train1,after,sup_train1_after_learning,4,4
13,supervised,train1,before,sup_train1_before_learning,4,4
14,supervised,train2,after,sup_train2_after_learning,5,5
15,supervised,train2,before,sup_train2_before_learning,5,5
16,unsupervised,test1,snapshot,unsup_test1,7,7
17,unsupervised,test2,snapshot,unsup_test2,6,6
18,unsupervised,test3,snapshot,unsup_test3,4,4
19,unsupervised,train1,after,unsup_train1_after_learning,9,9
20,unsupervised,train1,before,unsup_train1_before_learning,9,9
21,unsupervised,train2,after,unsup_train2_after_learning,6,6
22,unsupervised,train2,before,unsup_train2_before_learning,6,6

In [45]:
# The raw supplied rows behind one label (the equivalent of info['naive_test1']).
db.query("""
    SELECT recording_id, mouse, date, block, session_number,
           reward_type, stimulus, stimulus_ids_json, note
    FROM experiment_rows
    WHERE experiment = ?
    ORDER BY mouse, date, block, source_row
""", ["naive_test1"])

,recording_id,mouse,date,block,session_number,reward_type,stimulus,stimulus_ids_json,note
0,LZ13_2024_05_15_1,LZ13,2024_05_15,1,1.0,None,"cirlce0,circle1,leaf0,leaf1,leaf2","[0.0, 1.0, 2.0, 3.0, null]",VR move when run
1,LZ13_2024_05_16_2,LZ13,2024_05_16,2,2.0,None,"rock0,rock1,brick0,brick1,brick5","[0.0, 1.0, 2.0, 3.0, null]",VR move when run
2,LZ16_2024_05_18_2,LZ16,2024_05_18,2,1.0,None,"cirlce0,circle1,circle2,leaf0,leaf1,leaf2","[0.0, 1.0, null, 2.0, 3.0, null]",VR move when run
3,LZ16_2024_05_19_1,LZ16,2024_05_19,1,2.0,None,"rock0,rock1,brick0,brick1,brick5","[0.0, 1.0, 2.0, 3.0, null]",VR move when run
4,TX108_2023_01_05_2,TX108,2023_01_05,2,1.0,None,"cirlce0,circle1,leaf0,leaf1","[0, 1, 2, 3]",VR move when run
5,TX109_2023_03_16_1,TX109,2023_03_16,1,1.0,None,"cirlce0,circle1,leaf0,leaf1","[2, 3, 0, 1]",VR move when run
6,TX119_2023_12_12_1,TX119,2023_12_12,1,1.0,None,"rock0,rock1,brick0,brick1,brick5","[0.0, 1.0, 2.0, 3.0, null]",VR move when run
7,TX123_2023_12_18_1,TX123,2023_12_18,1,1.0,None,"cirlce0,circle1,circle2,leaf0,leaf0_swap1,leaf...","[0.0, 1.0, null, 2.0, null, null, 3.0, null]",VR move when run
8,TX124_2023_12_23_1,TX124,2023_12_23,1,1.0,None,"cirlce0,circle1,circle2,leaf0,leaf1,leaf2","[0.0, 1.0, null, 2.0, 3.0, null]",VR move when run
9,TX139_2024_05_18_1,TX139,2024_05_18,1,1.0,None,"cirlce0,circle1,leaf0,leaf1,leaf2","[0.0, 1.0, 2.0, 3.0, null]",VR move when run
10,TX140_2024_05_31_1,TX140,2024_05_31,1,1.0,None,"cirlce0,circle1,leaf0,leaf1,leaf2","[0.0, 1.0, 2.0, 3.0, null]",VR move when run

## Mice with neural recordings

The old notebook hardcoded four mouse lists. Here they are derived from the
supplied experiment memberships and restricted to recordings that have a
published full-neural file. `primary_cohort` uses the mutually exclusive study
grouping: supervised, then unsupervised, then grating, then naive-only.

In [46]:
db.query("""
    SELECT m.primary_cohort,
           string_agg(m.mouse, ', ' ORDER BY m.mouse) AS mice,
           count(*) AS mouse_count,
           sum(m.recording_count) AS physical_recordings
    FROM mice AS m
    WHERE m.has_full_neural
    GROUP BY m.primary_cohort
    ORDER BY CASE m.primary_cohort
        WHEN 'supervised' THEN 1 WHEN 'unsupervised' THEN 2
        WHEN 'grating' THEN 3 WHEN 'naive' THEN 4 END
""")

,primary_cohort,mice,mouse_count,physical_recordings
0,supervised,"TX108, TX109, TX60, TX61, VR2",5,30.0
1,unsupervised,"DR10, DR15, TX104, TX105, TX119, TX123, TX83, ...",9,45.0
2,grating,"LZ13, LZ16, TX139",3,10.0
3,naive,"TX124, TX140",2,4.0

## Everything for one mouse

One row below is one physical imaging acquisition. `experiments_json` can hold
multiple labels because labels describe analytical roles; it does not mean the
neural file contains multiple sessions.

In [47]:
mouse = "TX108"

db.query("""
    SELECT recording_id, date, block, experiments_json,
           has_behavior, has_reduced_neural, has_full_neural, has_retinotopy
    FROM recordings
    WHERE mouse = ?
    ORDER BY date, block
""", [mouse])

,recording_id,date,block,experiments_json,has_behavior,has_reduced_neural,has_full_neural,has_retinotopy
0,TX108_2023_01_05_2,2023_01_05,2,"[""naive_test1""]",True,True,True,True
1,TX108_2023_03_13_1,2023_03_13,1,"[""sup_train1_before_learning""]",True,True,True,True
2,TX108_2023_03_22_1,2023_03_22,1,"[""sup_train1_after_learning""]",True,True,True,True
3,TX108_2023_03_25_1,2023_03_25,1,"[""sup_test1"", ""sup_train2_before_learning""]",True,True,True,True
4,TX108_2023_04_01_1,2023_04_01,1,"[""sup_train2_after_learning""]",True,True,True,True
5,TX108_2023_04_04_1,2023_04_04,1,"[""sup_test2""]",True,True,True,True
6,TX108_2023_04_07_1,2023_04_07,1,"[""sup_test3""]",True,True,True,True

In [48]:
# Every supplied file linked to that mouse's physical recordings.
db.query("""
    SELECT rf.recording_id, rf.experiment, rf.layer,
           rf.filename, round(rf.size_gib, 3) AS size_gib
    FROM recording_files AS rf
    JOIN recordings AS r USING (recording_id)
    WHERE r.mouse = ?
    ORDER BY rf.recording_id, rf.layer, rf.experiment
""", [mouse])

,recording_id,experiment,layer,filename,size_gib
0,TX108_2023_01_05_2,naive_test1,behavior,Beh_naive_test1.npy,0.403
1,TX108_2023_01_05_2,None,full_neural,TX108_2023_01_05_2_neural_data.npy,5.923
2,TX108_2023_01_05_2,None,reduced_neural,TX108_2023_01_05_2_SVD_dec.npy,0.137
3,TX108_2023_01_05_2,None,retinotopy,TX108_2023_01_05_trans.npz,0.002
4,TX108_2023_03_13_1,sup_train1_before_learning,behavior,Beh_sup_train1_before_learning.npy,0.116
5,TX108_2023_03_13_1,None,full_neural,TX108_2023_03_13_1_neural_data.npy,7.322
6,TX108_2023_03_13_1,None,reduced_neural,TX108_2023_03_13_1_SVD_dec.npy,0.162
7,TX108_2023_03_13_1,None,retinotopy,TX108_2023_03_13_trans.npz,0.003
8,TX108_2023_03_22_1,sup_train1_after_learning,behavior,Beh_sup_train1_after_learning.npy,0.106
9,TX108_2023_03_22_1,None,full_neural,TX108_2023_03_22_1_neural_data.npy,5.502
10,TX108_2023_03_22_1,None,reduced_neural,TX108_2023_03_22_1_SVD_dec.npy,0.142
11,TX108_2023_03_22_1,None,retinotopy,TX108_2023_03_22_trans.npz,0.003
12,TX108_2023_03_25_1,sup_test1,behavior,Beh_sup_test1.npy,0.168
13,TX108_2023_03_25_1,sup_train2_before_learning,behavior,Beh_sup_train2_before_learning.npy,0.168
14,TX108_2023_03_25_1,None,full_neural,TX108_2023_03_25_1_neural_data.npy,7.870
15,TX108_2023_03_25_1,None,reduced_neural,TX108_2023_03_25_1_SVD_dec.npy,0.158
16,TX108_2023_03_25_1,None,retinotopy,TX108_2023_03_25_trans.npz,0.003
17,TX108_2023_04_01_1,sup_train2_after_learning,behavior,Beh_sup_train2_after_learning.npy,0.132
18,TX108_2023_04_01_1,None,full_neural,TX108_2023_04_01_1_neural_data.npy,4.342
19,TX108_2023_04_01_1,None,reduced_neural,TX108_2023_04_01_1_SVD_dec.npy,0.127
20,TX108_2023_04_01_1,None,retinotopy,TX108_2023_04_01_trans.npz,0.002
21,TX108_2023_04_04_1,sup_test2,behavior,Beh_sup_test2.npy,0.151
22,TX108_2023_04_04_1,None,full_neural,TX108_2023_04_04_1_neural_data.npy,5.779
23,TX108_2023_04_04_1,None,reduced_neural,TX108_2023_04_04_1_SVD_dec.npy,0.144
24,TX108_2023_04_04_1,None,retinotopy,TX108_2023_04_04_trans.npz,0.003
25,TX108_2023_04_07_1,sup_test3,behavior,Beh_sup_test3.npy,0.158
26,TX108_2023_04_07_1,None,full_neural,TX108_2023_04_07_1_neural_data.npy,4.333
27,TX108_2023_04_07_1,None,reduced_neural,TX108_2023_04_07_1_SVD_dec.npy,0.124
28,TX108_2023_04_07_1,None,retinotopy,TX108_2023_04_07_trans.npz,0.002

In [49]:
# The same file inspection for the two naive-only mice from the old notebook.
db.query("""
    SELECT r.mouse, rf.recording_id, rf.experiment, rf.layer,
           rf.filename, round(rf.size_gib, 3) AS size_gib
    FROM recording_files AS rf
    JOIN recordings AS r USING (recording_id)
    WHERE r.mouse IN ('TX124', 'TX140')
    ORDER BY r.mouse, rf.recording_id, rf.layer, rf.experiment
""")

,mouse,recording_id,experiment,layer,filename,size_gib
0,TX124,TX124_2023_12_23_1,naive_test1,behavior,Beh_naive_test1.npy,0.403
1,TX124,TX124_2023_12_23_1,naive_test2,behavior,Beh_naive_test2.npy,0.267
2,TX124,TX124_2023_12_23_1,None,full_neural,TX124_2023_12_23_1_neural_data.npy,1.780
3,TX124,TX124_2023_12_23_1,None,reduced_neural,TX124_2023_12_23_1_SVD_dec.npy,0.066
4,TX124,TX124_2023_12_23_1,None,retinotopy,TX124_2023_12_23_trans.npz,0.001
5,TX124,TX124_2023_12_24_1,naive_test3,behavior,Beh_naive_test3.npy,0.401
6,TX124,TX124_2023_12_24_1,None,full_neural,TX124_2023_12_24_1_neural_data.npy,1.415
7,TX124,TX124_2023_12_24_1,None,reduced_neural,TX124_2023_12_24_1_SVD_dec.npy,0.058
8,TX124,TX124_2023_12_24_1,None,retinotopy,TX124_2023_12_24_trans.npz,0.001
9,TX124,TX124_2023_12_26_1,naive_test3,behavior,Beh_naive_test3.npy,0.401
10,TX124,TX124_2023_12_26_1,None,full_neural,TX124_2023_12_26_1_neural_data.npy,1.513
11,TX124,TX124_2023_12_26_1,None,reduced_neural,TX124_2023_12_26_1_SVD_dec.npy,0.061
12,TX124,TX124_2023_12_26_1,None,retinotopy,TX124_2023_12_26_trans.npz,0.001
13,TX140,TX140_2024_05_31_1,naive_test1,behavior,Beh_naive_test1.npy,0.403
14,TX140,TX140_2024_05_31_1,naive_test2,behavior,Beh_naive_test2.npy,0.267
15,TX140,TX140_2024_05_31_1,None,full_neural,TX140_2024_05_31_1_neural_data.npy,4.640
16,TX140,TX140_2024_05_31_1,None,reduced_neural,TX140_2024_05_31_1_SVD_dec.npy,0.111
17,TX140,TX140_2024_05_31_1,None,retinotopy,TX140_2024_05_31_trans.npz,0.002

## Train 1 selection

This little DataFrame replaces the nested `train_1_labels` dictionary. It is
registered as a DuckDB table, so the selection is one readable join. The naive
snapshot is a reference, not a before/after pair.

In [50]:
import pandas as pd

train1_labels = pd.DataFrame([
    ("supervised", "before", "sup_train1_before_learning"),
    ("supervised", "after", "sup_train1_after_learning"),
    ("unsupervised", "before", "unsup_train1_before_learning"),
    ("unsupervised", "after", "unsup_train1_after_learning"),
    ("grating", "before", "train1_before_grating"),
    ("grating", "after", "train1_after_grating"),
    ("naive", "reference", "naive_test1"),
], columns=["cohort", "phase", "experiment"])

db.register("train1_labels", train1_labels)
train1_labels

         cohort      phase                    experiment
0    supervised     before    sup_train1_before_learning
1    supervised      after     sup_train1_after_learning
2  unsupervised     before  unsup_train1_before_learning
3  unsupervised      after   unsup_train1_after_learning
4       grating     before         train1_before_grating
5       grating      after          train1_after_grating
6         naive  reference                   naive_test1

In [51]:
# Complete Train 1 recording selection, restricted to the intended cohort and
# to physical acquisitions with full neural data.
train1_recordings = db.query("""
    SELECT l.cohort, l.phase, l.experiment,
           m.mouse, m.recording_id, m.date, m.block,
           r.experiments_json
    FROM train1_labels AS l
    JOIN memberships AS m USING (experiment)
    JOIN recordings AS r USING (recording_id)
    JOIN mice AS mouse_info ON mouse_info.mouse = m.mouse
    WHERE r.has_full_neural
      AND mouse_info.primary_cohort = l.cohort
    ORDER BY l.cohort, m.mouse, l.phase, m.date, m.block
""")

train1_recordings

,cohort,phase,experiment,mouse,recording_id,date,block,experiments_json
0,grating,after,train1_after_grating,LZ13,LZ13_2024_05_28_1,2024_05_28,1,"[""test1_after_grating"", ""test2_after_grating"",..."
1,grating,after,train1_after_grating,LZ13,LZ13_2024_05_29_1,2024_05_29,1,"[""test1_after_grating"", ""test2_after_grating"",..."
2,grating,before,train1_before_grating,LZ13,LZ13_2024_05_15_1,2024_05_15,1,"[""naive_test1"", ""naive_test2"", ""test1_before_g..."
3,grating,before,train1_before_grating,LZ13,LZ13_2024_05_16_2,2024_05_16,2,"[""naive_test1"", ""test1_before_grating"", ""test2..."
4,grating,after,train1_after_grating,LZ16,LZ16_2024_05_31_2,2024_05_31,2,"[""test1_after_grating"", ""test2_after_grating"",..."
5,grating,after,train1_after_grating,LZ16,LZ16_2024_06_01_1,2024_06_01,1,"[""test1_after_grating"", ""test2_after_grating"",..."
6,grating,before,train1_before_grating,LZ16,LZ16_2024_05_18_2,2024_05_18,2,"[""naive_test1"", ""naive_test2"", ""test1_before_g..."
7,grating,before,train1_before_grating,LZ16,LZ16_2024_05_19_1,2024_05_19,1,"[""naive_test1"", ""test1_before_grating"", ""test2..."
8,grating,after,train1_after_grating,TX139,TX139_2024_05_31_1,2024_05_31,1,"[""test1_after_grating"", ""test2_after_grating"",..."
9,grating,before,train1_before_grating,TX139,TX139_2024_05_18_1,2024_05_18,1,"[""naive_test1"", ""naive_test2"", ""test1_before_g..."
10,naive,reference,naive_test1,TX124,TX124_2023_12_23_1,2023_12_23,1,"[""naive_test1"", ""naive_test2""]"
11,naive,reference,naive_test1,TX140,TX140_2024_05_31_1,2024_05_31,1,"[""naive_test1"", ""naive_test2""]"
12,supervised,after,sup_train1_after_learning,TX108,TX108_2023_03_22_1,2023_03_22,1,"[""sup_train1_after_learning""]"
13,supervised,before,sup_train1_before_learning,TX108,TX108_2023_03_13_1,2023_03_13,1,"[""sup_train1_before_learning""]"
14,supervised,after,sup_train1_after_learning,TX109,TX109_2023_04_07_1,2023_04_07,1,"[""sup_train1_after_learning""]"
15,supervised,before,sup_train1_before_learning,TX109,TX109_2023_03_27_1,2023_03_27,1,"[""sup_train1_before_learning""]"
16,supervised,after,sup_train1_after_learning,TX60,TX60_2021_05_04_1,2021_05_04,1,"[""sup_train1_after_learning""]"
17,supervised,before,sup_train1_before_learning,TX60,TX60_2021_04_10_1,2021_04_10,1,"[""sup_train1_before_learning""]"
18,supervised,after,sup_train1_after_learning,VR2,VR2_2021_04_06_1,2021_04_06,1,"[""sup_train1_after_learning""]"
19,supervised,before,sup_train1_before_learning,VR2,VR2_2021_03_20_1,2021_03_20,1,"[""sup_train1_before_learning""]"
20,unsupervised,after,unsup_train1_after_learning,DR10,DR10_2022_07_19_1,2022_07_19,1,"[""unsup_train1_after_learning""]"
21,unsupervised,before,unsup_train1_before_learning,DR10,DR10_2022_07_12_1,2022_07_12,1,"[""unsup_train1_before_learning""]"
22,unsupervised,after,unsup_train1_after_learning,DR15,DR15_2022_10_19_1,2022_10_19,1,"[""unsup_train1_after_learning""]"
23,unsupervised,before,unsup_train1_before_learning,DR15,DR15_2022_10_09_1,2022_10_09,1,"[""unsup_train1_before_learning""]"
24,unsupervised,after,unsup_train1_after_learning,TX104,TX104_2022_10_20_1,2022_10_20,1,"[""unsup_train1_after_learning""]"
25,unsupervised,before,unsup_train1_before_learning,TX104,TX104_2022_10_12_1,2022_10_12,1,"[""unsup_train1_before_learning""]"
26,unsupervised,after,unsup_train1_after_learning,TX105,TX105_2022_10_19_2,2022_10_19,2,"[""unsup_train1_after_learning""]"
27,unsupervised,before,unsup_train1_before_learning,TX105,TX105_2022_10_08_2,2022_10_08,2,"[""unsup_train1_before_learning""]"
28,unsupervised,after,unsup_train1_after_learning,TX119,TX119_2023_12_23_1,2023_12_23,1,"[""unsup_train1_after_learning""]"
29,unsupervised,before,unsup_train1_before_learning,TX119,TX119_2023_12_14_1,2023_12_14,1,"[""unsup_train1_before_learning""]"
30,unsupervised,after,unsup_train1_after_learning,TX123,TX123_2024_01_02_1,2024_01_02,1,"[""unsup_train1_after_learning""]"
31,unsupervised,before,unsup_train1_before_learning,TX123,TX123_2023_12_21_1,2023_12_21,1,"[""unsup_train1_before_learning""]"
32,unsupervised,after,unsup_train1_after_learning,TX83,TX83_2022_08_29_1,2022_08_29,1,"[""unsup_train1_after_learning""]"
33,unsupervised,before,unsup_train1_before_learning,TX83,TX83_2022_08_17_1,2022_08_17,1,"[""unsup_train1_before_learning""]"
34,unsupervised,after,unsup_train1_after_learning,TX85,TX85_2022_06_17_1,2022_06_17,1,"[""unsup_train1_after_learning""]"
35,unsupervised,before,unsup_train1_before_learning,TX85,TX85_2022_06_14_1,2022_06_14,1,"[""unsup_train1_before_learning""]"
36,unsupervised,after,unsup_train1_after_learning,TX88,TX88_2022_06_17_2,2022_06_17,2,"[""unsup_train1_after_learning""]"
37,unsupervised,before,unsup_train1_before_learning,TX88,TX88_2022_06_13_2,2022_06_13,2,"[""unsup_train1_before_learning""]"

`train1_recordings` is itself registered because `db.query(...)` returns a
DataFrame; register it before the summary query:

In [52]:
db.register("train1_recordings", train1_recordings)

db.query("""
    SELECT cohort, phase,
           count(DISTINCT mouse) AS mice,
           count(DISTINCT recording_id) AS physical_recordings
    FROM train1_recordings
    GROUP BY cohort, phase
    ORDER BY cohort, phase
""")

         cohort      phase  mice  physical_recordings
0       grating      after     3                    5
1       grating     before     3                    5
2         naive  reference     2                    2
3    supervised      after     4                    4
4    supervised     before     4                    4
5  unsupervised      after     9                    9
6  unsupervised     before     9                    9

## Load only after selecting

The SQL catalog resolves exact filenames without downloading arrays. Once a
row has been chosen, `db.load` delegates one safe load to the private filesystem layer:

```python
recording_id = "TX108_2023_03_13_1"
behavior = db.load(
    recording_id, "behavior",
    experiment="sup_train1_before_learning",
)
svd = db.load(recording_id, "reduced_neural")
retinotopy = db.load(recording_id, "retinotopy")
```

Use `full_neural` only after checking `recording_files.size_gib`; those files
are several GiB. The selection remains an ordinary SQL row throughout.